apiVersion: v1
kind: Pod
metadata:
  annotations:
    "fargate.eks.amazonaws.com/admit": "false"
    "fargate.eks.amazonaws.com/admitMessage": "Pod not supported: fields not supported: HostNetwork"
  name: init-security-context
  namespace: eks-fargate-namespace
  labels:
    "eks.amazonaws.com/fargate-profile": "my-profile"
spec:
  schedulerName: fargate-scheduler
  hostNetwork: true
  initContainers:
    - image: nginx:alpine
      name: nginx
  containers:
    - image: nginx:alpine
      name: nginx
      volumeMounts:
        - mountPath: /mnt/scratch
          name: scratch
  volumes:
    - name: scratch
      emptyDir: {}
