apiVersion: v1
kind: Pod
metadata:
  annotations:
    "fargate.eks.amazonaws.com/admit": "false"
    "fargate.eks.amazonaws.com/admitMessage": "Pod not supported: port contains HostIP or HostPort"
    "fargate.eks.amazonaws.com/runContainerValidation": "true"
    "fargate.eks.amazonaws.com/containerAdmitMessage": "port contains HostIP or HostPort"
  name: hostport-pod
  namespace: eks-fargate-namespace
  labels:
    "eks.amazonaws.com/fargate-profile": "my-profile"
spec:
  schedulerName: fargate-scheduler
  containers:
  - image: nginx:alpine
    name: nginx
    ports:
    - name: http
      port: 80
      hostPort: 8000
